#!/bin/bash
#SBATCH --array=0-1  # Adjust this based on your param rows
#SBATCH --job-name=bq_ice
#SBATCH --output=bq%j.log     
#SBATCH --nodes=1
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --partition=capacity    
#SBATCH --gres=gpu:1
#SBATCH --mem=100G
#SBATCH --time=7-00:00:00




export TMPDIR=/local_scratch
module purge
module load gnu12/12.4.0 
module load openmpi4
module load cmake/3.24.2

source ~/miniconda3/etc/profile.d/conda.sh
conda activate emukit_env2
source /home/ekempke/software/plumed2_ice/sourceme.sh




# Get the 'name' from the Python script's output

pwd; hostname; date
echo "===="
echo "Number of cores/node:$SLURM_CPUS_ON_NODE"
echo "Number of cores/task:$SLURM_CPUS_PER_TASK"

echo "SLURM_JOBID=$SLURM_JOBID"
echo "SLURM_JOB_NODELIST=$SLURM_JOB_NODELIST"
echo "SLURM_NNODES=$SLURM_NNODES "
echo "working directory= $SLURM_SUBMIT_DIR "
echo "tmp directory=$TMPDIR"
echo "NPROCS=$SLURM_NPROCS"
echo "Number of CPUs per task=$SLURM_CPUS_PER_TASK"
echo "Count of processors available to the job on this node=$SLURM_JOB_CPUS_PER_NODE"
echo "Number of CPUs requested per allocated GPU=$SLURM_CPUS_PER_GPU"
echo "Number of GPUs requested=$SLURM_GPUS"
echo "Number of tasks=$SLURM_NTASKS"

# no coredumps
ulimit -S -c 0
ulimit -s unlimited
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

# Create a scratch directory for the job
prologue()
{
    mkdir -p $TMPDIR/$USER/$SLURM_JOBID/colvars
    cp -r $SLURM_SUBMIT_DIR/simulation_essentials/* $TMPDIR/$USER/$SLURM_JOBID
    cp -r $SLURM_SUBMIT_DIR/bayesquad_pt_ice.py $TMPDIR/$USER/$SLURM_JOBID
    cp -r $SLURM_SUBMIT_DIR/params.csv $TMPDIR/$USER/$SLURM_JOBID

    cd $TMPDIR/$USER/$SLURM_JOBID
    echo "Job started at: $(date)" > slurm-job-time.log
}

# Handle both normal and cancelled exit
epilogue()
{
    NAME=$(cat run_name.txt)
    echo "Job ended at: $(date)" >> slurm-job-time.log

    # Decide folder prefix
    if [ "$CANCELLED" = true ]; then
        PREFIX="cancelled_results_"
    else
        PREFIX="results_"
    fi

    RESULT_DIR="$SLURM_SUBMIT_DIR/$rerun_point"
    mkdir -p "$RESULT_DIR"
    cp -r $TMPDIR/$USER/$SLURM_JOBID/* "$RESULT_DIR"
    rm -rf $TMPDIR/$USER/$SLURM_JOBID
}

# Trap SLURM cancel signals and flag them
cancel_handler()
{
    CANCELLED=true
    epilogue
    exit 1
}

# Main execution block
trap cancel_handler SIGTERM SIGINT
trap epilogue EXIT

prologue
CANCELLED=false

python bayesquad_pt_ice.py &> python.out


exit
